# Generated by Django 4.2.16 on 2024-11-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=50)),
                ('variation', models.CharField(max_length=50)),
                ('program_time', models.CharField(max_length=50)),
                ('posology', models.CharField(max_length=255)),
                ('variation_code', models.CharField(max_length=50, unique=True)),
                ('variation_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('info_received', models.BooleanField(default=False)),
                ('control_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logistic_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('internal_code', models.CharField(max_length=50)),
                ('universe', models.CharField(max_length=50)),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.productvariation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logistic_codification', models.CharField(blank=True, max_length=50, null=True)),
                ('inventory_date', models.DateField(blank=True, null=True)),
                ('inventory_on_hand', models.PositiveIntegerField(blank=True, null=True)),
                ('value_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_on_hand_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_progress_delivery', models.PositiveIntegerField(blank=True, null=True)),
                ('total_predicted_inventory', models.PositiveIntegerField(blank=True, null=True)),
                ('total_predicted_inventory_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='api.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='api.warehouse')),
            ],
        ),
    ]
