# Generated by Django 4.2.16 on 2024-11-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
